### ISSUE TITLE
Java11 support

### ISSUE THREAD

**Issue by tonivade** [tonivade/claudb#21]

**Comment by junoyoon** [comment]
@tonivade 
First of all.. thx for making such a great application. 
You mentioned that you're making this for fun.. 
Wow.. I can not believe this can be done just for fun. You're great!!

By the way, I'd like to use this as a mock redis server for unit test.
Does not it support java11?  What happens if I run caludb in java11?
Could u explain little bit plz?

**Comment by tonivade** [comment]
Thanks for you kind words!

About your question, yes, it should support 100% java11 (even java17) without problems. Honestly I don't remember why I created this issue in first place.

**Comment by junoyoon** [comment]
OK. Thank you for clearing this.
I'll use this with easy from now on.
TTTTHHHHAAANNNKKKS!!
